init: start task
ClevertecFrontendLab/sprint1-Marina2609 pull request #1
Opened 2023-02-01 16:46 UTC by Marina2609

2023-02-01 16:49 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675270154/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675270154/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675270154/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675270154/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675270154/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675270154/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675270154/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675270154/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675270154/content-window.png)

2023-02-01 17:00 UTC, klichkovskiy requested changes

2023-02-01 17:00 UTC, klichkovskiy commented on src/app/components/cards/cards.jsx
> +export const Cards = (props) => (
link на книгу должен быть на всей карточке!

2023-02-02 09:02 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675328527/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675328527/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675328527/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675328527/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675328527/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675328527/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675328527/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675328527/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675328527/content-window.png)

2023-02-02 09:15 UTC, klichkovskiy requested changes

2023-02-02 09:15 UTC, klichkovskiy commented on src/app/components/cards/cards.jsx
> +          <NavLink to={`/book/${card.id}`} state={{ props: card }}>
![image](https://user-images.githubusercontent.com/62481116/216281835-91d4734c-1446-47ed-ae74-47753672bdf0.png)
Все еще скрол

2023-02-02 09:15 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +        <div className='book-title'>
![image](https://user-images.githubusercontent.com/62481116/216282007-a99eb59d-0b8b-4310-a7f8-b83e1525a8ce.png)
на книге тоже скрол

2023-02-02 13:33 UTC, klichkovskiy approved these changes

2023-02-02 13:36 UTC, merged